name: Build vLLM Images (latest release)

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  build-vllm:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - dockerfile: Dockerfile
            name: nvidia
            platform: linux/amd64
          - dockerfile: Dockerfile.cpu
            name: cpu
            platform: linux/amd64
          
    steps:
      - name: Remove unnecessary files
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Check code
        uses: actions/checkout@v4

      - name: Clone vllm repo
        id: checkout
        run: |
          git clone https://github.com/vllm-project/vllm.git vllm
          cd vllm
          LATEST_TAG=$(git describe --tags --abbrev=0)
          git checkout "tags/$LATEST_TAG" -b latest
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        if: ${{ matrix.target.name != 'nvidia' }}
        uses: docker/build-push-action@v6
        with:
          context: ./vllm
          file: ./vllm/${{ matrix.target.dockerfile }}
          platforms: ${{ matrix.target.platform }}
          push: true
          tags: |
            uptospace/vllm:${{ steps.checkout.outputs.latest_tag }}-${{ matrix.target.name }}
            
      - name: Pull and re-tag/push nvidia image
        if: ${{ matrix.target.name == 'nvidia' }}
        run: |
          echo "Pulling official vllm/vllm-openai:${{ steps.checkout.outputs.latest_tag }}..."
          docker pull vllm/vllm-openai:${{ steps.checkout.outputs.latest_tag }}
          echo "Tagging as uptospace/vllm:${{ steps.checkout.outputs.latest_tag }}..."
          docker tag vllm/vllm-openai:${{ steps.checkout.outputs.latest_tag }} uptospace/vllm:${{ steps.checkout.outputs.latest_tag }}
          echo "Pushing uptospace/vllm:${{ steps.checkout.outputs.latest_tag }}..."
          docker push uptospace/vllm:${{ steps.checkout.outputs.latest_tag }}


