name: Build vLLM runai Images (latest release)

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  build-vllm:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - baseimage: uptospace/vllm
            name: cpu
            platform: linux/amd64
          - baseimage: uptospace/vllm
            name: arm
            platform: linux/arm64
          - baseimage: vllm/vllm-openai
            name: nvidia
            platform: linux/amd64
          - baseimage: uptospace/vllm
            name: amd
            platform: linux/amd64
          - baseimage: uptospace/vllm
            name: tpu
            platform: linux/amd64
          
    steps:
      - name: Check code
        uses: actions/checkout@v4
      
      - name: Clone vllm repo
        id: checkout
        run: |
          git clone https://github.com/vllm-project/vllm.git vllm
          cd vllm
          LATEST_TAG=$(git describe --tags --abbrev=0)
          git checkout "tags/$LATEST_TAG" -b latest
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.runai
          platforms: ${{ matrix.target.platform }}
          build-args: BASE_IMAGE=${{ matrix.target.name == 'nvidia' && matrix.target.baseimage || format('{0}:{1}-{2}', matrix.target.baseimage, steps.checkout.outputs.latest_tag, matrix.target.name) }}
          push: true
          tags: |
            uptospace/vllm:${{ matrix.target.name == 'nvidia' && steps.checkout.outputs.latest_tag || format('{0}-{1}', steps.checkout.outputs.latest_tag, matrix.target.name) }}-runai
